---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: kubedoom
  name: kube-doom-deployment
  labels:
    app: kubedoom-0-5-0
spec:
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  replicas: 1
  selector:
    matchLabels:
      app: kubedoom-0-5-0
  template:
    metadata:
      labels:
        app: kubedoom-0-5-0
    spec:
      hostNetwork: true
      serviceAccountName: kubedoom
      containers:
      - name: kubedoom-0-5-0
        image: storaxdev/kubedoom:0.5.0
        ports:
        - protocol: TCP
          containerPort: 5900
          
          
          
          